// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1_7pM_z4P3xj5PAfeg39s5PsYBfrp5g',
    appId: '1:1012679868774:android:2bdad1cc08a0de362688a7',
    messagingSenderId: '1012679868774',
    projectId: 'chatflutter-d8a07',
    storageBucket: 'chatflutter-d8a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcVrlq-GLMgjTWSxaIIPjiPiZFP9uqLs',
    appId: '1:1012679868774:ios:f506da345242ae7c2688a7',
    messagingSenderId: '1012679868774',
    projectId: 'chatflutter-d8a07',
    storageBucket: 'chatflutter-d8a07.appspot.com',
    androidClientId: '1012679868774-tb2vi2l0b6fuqeea3los6m2khil4gfqg.apps.googleusercontent.com',
    iosClientId: '1012679868774-iu3ig22fhnljjo65jbmkqgcjhfsj9fi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatonlinefirebase.chatonlinefirebase',
  );
}
